language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2
  - $HOME/travis
  
script:
  - mvn clean test
  
after_success:
  - mvn sonar:sonar -Dsonar.host.url=https:/sonarqube.com -Dsonar.login=${SONARQUBE_TOKEN}
